# Generated by Django 5.0.4 on 2024-04-21 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0004_student_cell'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='photo',
            field=models.ImageField(blank=True, upload_to=''),
        ),
    ]
